### ISSUE TITLE
Multi-Modal CelebA-HQ Dataset

### ISSUE THREAD

**Issue by thinkerthinker** [weihaox/TediGAN#1]
Hello, I'm excited about your excellent work!
I want to download Multi-Modal CelebA-HQ Dataset described in your paper, according to the URL provided by https://drive.google.com/drive/folders/1eVrGKfkbw7bh9xPcX8HJa-qWQTD9aWvf.
Sadly, I can't access it. Is the URL correct? How can I download this dataset?
I look forward to your reply!

**Comment by weihaox** [comment]
fixed.

**Comment by thinkerthinker** [comment]
Thanks.
