### ISSUE TITLE
style mix

### ISSUE THREAD

**Issue by RookieInAI** [weihaox/TediGAN#2]
about style mixing，how to select the layer to be replaced according to the text content

**Comment by weihaox** [comment]
We have conducted a layer-wise analysis ([Section 3.4](https://arxiv.org/pdf/2012.03308.pdf)) to select the related attributes and illustrated with an example.  The analysis is empirical and attributes in the same layer might be entangled if occurred in one sentence. Please refer to the paper for more details.
