### ISSUE TITLE
File "invert_v2.py", line 32     parser.add_argument('--learning_rate', type=float, default=0.01,          ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Kesavan-Raman** [weihaox/TediGAN#3]
Getting this kind of error, Please Help me Sir/Madam

**Comment by weihaox** [comment]
It looks like the error is caused by the version of python and interpreter (I use python 3.6 and Anaconda). For quick start, you can run the colab demo instead.

**Comment by Kesavan-Raman** [comment]
Sir I Run in Colab only sir But i got this kind of error, any other suggestion sir ? Please help me

**Comment by weihaox** [comment]
Hi, @Kesavan-Raman

The right parenthesis was accidentally deleted when I cleaned up the code. I have [fixed](https://github.com/weihaox/TediGAN/commit/311c9dff144b320da59239ecdc67fefa944f9df6) it. Sorry for the inconvience. Please try again. 

If encountering the problem of 'No pre-trained weights will be loaded!', please change ```MODEL_DIR = os.path.join('models', 'pretrain')``` to ```MODEL_DIR = os.path.join('idinvert_pytorch', 'models', 'pretrain')``` in the Colab.

**Comment by Kesavan-Raman** [comment]
Thank you Sir It's Now working 😇😇

**Comment by Kesavan-Raman** [comment]
Thank you Sir It's Now working 😇😇
