### ISSUE TITLE
How to run pretrained model on colab?

### ISSUE THREAD

**Issue by ganimage007** [weihaox/TediGAN#4]
i am unable to run the pretrained model ,
it gives error as
**File "/content/TediGAN/idinvert_pytorch/models/base_module.py", line 94, in __init__
    for key, val in model_settings.MODEL_POOL[model_name].items():
KeyError: 'stylegan_ffhq256'**

**Comment by weihaox** [comment]
I just ran the codes and didn't encounter the problem you said. Maybe you can re-run the codes.
<img width="1002" alt="截屏2021-03-04 下午9 46 50" src="https://user-images.githubusercontent.com/54136324/109973825-d24d0880-7d33-11eb-819e-b50b37417210.png">

**Comment by ganimage007** [comment]
Yeah thanks,

**Comment by ozamanan** [comment]
![Screenshot from 2021-03-04 19-52-12](https://user-images.githubusercontent.com/21983436/110051100-3a472300-7d23-11eb-84ae-5765f4b204ea.png)
Hello, I have been facing this problem. I tried running it multiple times

**Comment by ganimage007** [comment]
Hello sir,
I am getting this kind of output, kindly help me with this.
Thanks
